import { db } from '../index'
import { sql } from 'drizzle-orm'
import { decorativeMaterials, phytosanitaryProducts } from '../schema'

// Real user IDs
const ADMIN = '8490ab62-a88e-4e00-8e17-a307922f9a40'
const KARIM = 'e4451d4f-3ce7-4608-a125-b581847a0be3' // etudes_chef

async function main() {
  console.log('Seeding Études dummy data (decorative materials + phytosanitary products)…')

  // ── 1. Matières décoratives (FOR-ET-03) ──────────────────────────────────────
  await db.insert(decorativeMaterials).values([
    {
      code: 'MD-001',
      name: 'Galets de rivière blancs',
      mainMaterial: 'Pierre naturelle',
      aspect: 'Roulé, poli',
      color: 'Blanc / ivoire',
      caliber: '20–40 mm',
      waterAbsorption: '< 1 %',
      packaging: 'Sac 25 kg',
      usedInterior: false,
      usedExterior: true,
      handling: 'Manutention manuelle ou mécanique selon volume. Éviter les chutes sur surfaces dures.',
      packagingDetails: 'Sacs tissés de 25 kg, conditionnement sur palettes de 50 sacs.',
      storageConditions: 'Stocker sur surface plane et sèche. Protéger de la boue.',
      maintenance: 'Nettoyage périodique au jet d\'eau. Retrait des déchets végétaux.',
      notes: 'Usage en enrochement décoratif, bords de bassins, allées minérales.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'MD-002',
      name: 'Gravier concassé gris anthracite',
      mainMaterial: 'Calcaire concassé',
      aspect: 'Anguleux, mat',
      color: 'Gris anthracite',
      caliber: '10–20 mm',
      waterAbsorption: '2–3 %',
      packaging: 'Vrac / Big-bag 1 tonne',
      usedInterior: false,
      usedExterior: true,
      handling: 'Livraison en benne ou big-bag. Répandre à la pelle ou mécaniquement.',
      packagingDetails: 'Big-bags de 1 tonne ou livraison en vrac.',
      storageConditions: 'Stockage en extérieur accepté. Éviter mélange avec autres granulats.',
      maintenance: 'Désherbage régulier. Griffage annuel pour homogénéiser la surface.',
      notes: 'Idéal pour allées minérales, espaces modernes et jardins contemporains.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'MD-003',
      name: 'Écorces de pin broyées',
      mainMaterial: 'Bois — pin maritime',
      aspect: 'Fibreux, naturel',
      color: 'Brun orangé',
      caliber: '20–60 mm',
      waterAbsorption: 'Élevée — hygroscopique',
      packaging: 'Sac 70 L / Balle 3 m³',
      usedInterior: true,
      usedExterior: true,
      handling: 'Épandage manuel à la fourche ou mécaniquement.',
      packagingDetails: 'Sacs de 70 litres ou balles compressées de 3 m³.',
      storageConditions: 'Conserver à l\'abri de l\'humidité excessive. Ne pas laisser en contact avec le sol nu sur longue durée.',
      maintenance: 'Renouvellement conseillé tous les 2–3 ans. Griffage en début de saison.',
      notes: 'Paillis organique pour massifs, pieds d\'arbres. Améliore la rétention d\'eau.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'MD-004',
      name: 'Ardoise noire en dalles irrégulières',
      mainMaterial: 'Ardoise naturelle',
      aspect: 'Feuilleté, irrégulier',
      color: 'Noir bleuté',
      caliber: 'Épaisseur 1–3 cm, dimensions variables',
      waterAbsorption: '< 0,5 %',
      packaging: 'Palette 300 kg',
      usedInterior: true,
      usedExterior: true,
      handling: 'Manipulation avec précaution — matériau fragile. Port de gants recommandé.',
      packagingDetails: 'Palettes cerclées de 300 kg, film protecteur.',
      storageConditions: 'Stockage à plat sur palette. Éviter empilements non protégés.',
      maintenance: 'Nettoyage à l\'eau claire. Appliquer un hydrofuge si usage en zone humide.',
      notes: 'Revêtement de sol décoratif, margelles de bassin, habillage de murs.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'MD-005',
      name: 'Sable de marbre blanc',
      mainMaterial: 'Marbre concassé',
      aspect: 'Fin, brillant',
      color: 'Blanc pur',
      caliber: '0–4 mm',
      waterAbsorption: '< 1 %',
      packaging: 'Sac 25 kg / Vrac',
      usedInterior: true,
      usedExterior: true,
      handling: 'Épandage manuel. Éviter contact prolongé avec matériaux acides.',
      packagingDetails: 'Sacs 25 kg ou livraison vrac.',
      storageConditions: 'À l\'abri de l\'humidité et des contaminants colorés.',
      maintenance: 'Remplacement partiel si coloration apparaît. Nettoyage jet d\'eau.',
      notes: 'Fond de bassin décoratif, massifs minéraux zen, cours intérieures.',
      isActive: true,
      createdBy: ADMIN,
    },
    {
      code: 'MD-006',
      name: 'Dalles béton aspect pierre ocre',
      mainMaterial: 'Béton pigmenté',
      aspect: 'Structuré, imitation pierre',
      color: 'Ocre / sable',
      caliber: '40 × 40 × 4 cm',
      waterAbsorption: '4–6 %',
      packaging: 'Palette 60 dalles',
      usedInterior: false,
      usedExterior: true,
      handling: 'Poser sur lit de sable ou mortier. Joints au sable fin ou mortier.',
      packagingDetails: 'Palettes de 60 unités (= 9,6 m²), filmées.',
      storageConditions: 'Stockage en extérieur sur palette. Protéger des taches avant pose.',
      maintenance: 'Nettoyage haute pression. Traitement hydrofuge annuel recommandé.',
      notes: 'Allées piétonnes, terrasses, patios. Compatible avec arrosage intégré.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'MD-007',
      name: 'Pouzzolane rouge volcanique',
      mainMaterial: 'Roche volcanique',
      aspect: 'Poreux, granuleux',
      color: 'Rouge brique / bordeaux',
      caliber: '10–20 mm',
      waterAbsorption: 'Élevée — très poreuse',
      packaging: 'Sac 20 L / Big-bag',
      usedInterior: true,
      usedExterior: true,
      handling: 'Épandage à la pelle. Matériau léger, facile à travailler.',
      packagingDetails: 'Sacs de 20 litres ou big-bags de 750 kg.',
      storageConditions: 'Stockage sec de préférence. Éviter tassement excessif.',
      maintenance: 'Peu d\'entretien requis. Désherbage ponctuel.',
      notes: 'Paillis minéral drainant, fond de pot cactées/succulentes, décoration zen.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'MD-008',
      name: 'Bois composite terrasse — lame IPE',
      mainMaterial: 'Bois tropical IPE',
      aspect: 'Lisse, veiné',
      color: 'Brun doré naturel',
      caliber: 'Lame 145 × 21 mm, longueur variable',
      waterAbsorption: '< 3 %',
      packaging: 'Fagots de 10 lames',
      usedInterior: true,
      usedExterior: true,
      handling: 'Pose sur lambourdes acier inox. Visserie inox recommandée. Laisser joint de dilatation.',
      packagingDetails: 'Fagots de 10 lames, film plastique de protection.',
      storageConditions: 'Sous abri ou bâché. Éviter contact direct sol humide.',
      maintenance: 'Ponçage et application huile teck annuellement. Nettoyage haute pression au printemps.',
      notes: 'Terrasses, passerelles, platelages. Bois certifié FSC.',
      isActive: true,
      createdBy: ADMIN,
    },
  ]).onConflictDoNothing()

  console.log('  ✓ 8 matières décoratives insérées')

  // ── 2. Produits phytosanitaires (FOR-ET-05) ───────────────────────────────────
  await db.insert(phytosanitaryProducts).values([
    {
      code: 'PP-001',
      productType: 'insecticide',
      commercialName: 'Confidor 200 SL',
      approvalNumber: 'AMM-2019-0041',
      activeIngredient: 'Imidaclopride 200 g/L',
      formulation: 'Concentré soluble (SL)',
      concentration: '200 g/L',
      usageDose: '0,5–1 mL/L d\'eau',
      targetPests: 'Pucerons, aleurodes, cochenilles, thrips',
      targetCrop: 'Plantes ornementales, arbustes, gazon',
      reEntryDelay: '24 heures',
      technicalDocs: 'Fiche de données de sécurité disponible. Homologué Tunisie.',
      packaging: 'Flacon 250 mL, Bidon 1 L',
      toxicologicalClass: 'Nocif — Xi',
      ppe: 'Gants nitrile, lunettes de protection, masque FFP2, combinaison de travail.',
      storageConditions: 'Local fermé à clé, 5–30 °C, à l\'abri de l\'humidité et du gel. Séparer des engrais.',
      preUseInstructions: 'Vérifier conditions météo (pas de vent > 3 m/s, pas de pluie prévue 4h). Préparer solution à l\'ombre.',
      duringUseInstructions: 'Porter tous les EPI. Ne pas pulvériser pendant floraison active. Éviter dérive.',
      wasteDisposal: 'Rincer emballages 3 fois. Déposer en déchetterie agréée. Ne pas vider dans égouts.',
      notes: 'Efficace en application foliaire ou drench racinaire. Respecter délai de retour chantier.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'PP-002',
      productType: 'fongicide',
      commercialName: 'Score 250 EC',
      approvalNumber: 'AMM-2017-0088',
      activeIngredient: 'Difénoconazole 250 g/L',
      formulation: 'Concentré émulsifiable (EC)',
      concentration: '250 g/L',
      usageDose: '0,4 mL/L d\'eau',
      targetPests: 'Oïdium, tavelure, rouilles, alternariose',
      targetCrop: 'Rosiers, arbustes à fleurs, plantes ornementales',
      reEntryDelay: '48 heures',
      technicalDocs: 'Fiche technique Syngenta disponible.',
      packaging: 'Flacon 100 mL, Bidon 1 L',
      toxicologicalClass: 'Danger — GHS07/GHS09',
      ppe: 'Gants résistants aux produits chimiques, visière, tablier PVC, bottes.',
      storageConditions: '0–35 °C, récipient bien fermé, à l\'abri de la lumière directe.',
      preUseInstructions: 'Agiter avant usage. Appliquer en début d\'infestation ou préventif. Température optimale 15–25 °C.',
      duringUseInstructions: 'Traiter tôt le matin ou le soir. Couvrir toutes les surfaces foliaires.',
      wasteDisposal: 'Triple rinçage des emballages. Collecte par organisme agréé.',
      notes: 'Action préventive et curative. Alterner avec d\'autres familles chimiques pour éviter résistances.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'PP-003',
      productType: 'herbicide',
      commercialName: 'Roundup ProActive',
      approvalNumber: 'AMM-2018-0152',
      activeIngredient: 'Glyphosate 360 g/L',
      formulation: 'Concentré soluble (SL)',
      concentration: '360 g/L',
      usageDose: '5–10 mL/L d\'eau selon la cible',
      targetPests: 'Mauvaises herbes annuelles et vivaces à feuilles larges et graminées',
      targetCrop: 'Zones non agricoles, allées, contours de massifs',
      reEntryDelay: '6 heures (feuillage sec)',
      technicalDocs: 'Bayer — fiche produit disponible. Usage restreint zones sensibles.',
      packaging: 'Bidon 1 L, Bidon 5 L',
      toxicologicalClass: 'Attention — GHS07',
      ppe: 'Gants nitrile longue durée, lunettes, masque A2P2, bottes imperméables.',
      storageConditions: 'Conserver entre 0 et 40 °C. Fermé hermétiquement. Loin des denrées alimentaires.',
      preUseInstructions: 'Ne pas traiter si pluie prévue dans les 6h. Protéger plantes ornementales voisines.',
      duringUseInstructions: 'Viser uniquement les mauvaises herbes. Éviter tout contact avec plantes désirables.',
      wasteDisposal: 'Ne jamais vider dans cours d\'eau. Collecte déchets phytosanitaires.',
      notes: 'Herbicide systémique total. À utiliser ponctuellement. Délai action visible : 5–7 jours.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'PP-004',
      productType: 'acaricide',
      commercialName: 'Vertimec 018 EC',
      approvalNumber: 'AMM-2020-0037',
      activeIngredient: 'Abamectine 18 g/L',
      formulation: 'Concentré émulsifiable (EC)',
      concentration: '18 g/L',
      usageDose: '1,5–2 mL/L d\'eau',
      targetPests: 'Acariens tétranyques, acariens des bourgeons',
      targetCrop: 'Arbustes ornementaux, plantes de haies, palmiers',
      reEntryDelay: '48 heures',
      technicalDocs: 'Syngenta — fiche sécurité référencée.',
      packaging: 'Flacon 250 mL, Bidon 1 L',
      toxicologicalClass: 'Dangereux — GHS06/GHS09 (toxique abeilles)',
      ppe: 'Combinaison intégrale, gants nitrile, masque A2P3, lunettes étanches.',
      storageConditions: '5–25 °C, à l\'abri de la lumière et gel.',
      preUseInstructions: 'Ne pas appliquer en période de floraison. Alerter apiculteurs voisins 48h avant.',
      duringUseInstructions: 'Application foliaire. Traiter par temps calme, sans vent. Couvrir entièrement le feuillage.',
      wasteDisposal: 'Emballages vides : triple rinçage, collecte phytosanitaire agréée.',
      notes: 'Acaricide de contact et ingestion. Très efficace contre formes résistantes. Renouveler si nécessaire à 7 jours.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'PP-005',
      productType: 'engrais',
      commercialName: 'Osmocote Exact 5-6M',
      approvalNumber: null,
      activeIngredient: 'NPK 15-9-12 + oligo-éléments',
      formulation: 'Granulés à libération lente enrobés',
      concentration: 'NPK 15-9-12 + 2 MgO',
      usageDose: '3–5 g/L de substrat (pots) / 25–35 g/m² (pleine terre)',
      targetPests: null,
      targetCrop: 'Toutes plantes ornementales, arbustes, vivaces, gazon',
      reEntryDelay: 'Aucun',
      technicalDocs: 'ICL Specialty Fertilizers — fiche produit.',
      packaging: 'Sac 2 kg, Sac 5 kg',
      toxicologicalClass: 'Non classé (faible risque)',
      ppe: 'Gants de jardinage. Lavage des mains après manipulation.',
      storageConditions: 'Lieu sec, fermé, à l\'abri de la chaleur excessive (< 35 °C).',
      preUseInstructions: 'Incorporer au substrat lors de la plantation ou en surface.',
      duringUseInstructions: 'Ne pas dépasser la dose recommandée — risque de brûlure racinaire.',
      wasteDisposal: 'Emballages vides dans ordures ménagères. Produit biodégradable.',
      notes: 'Libération sur 5–6 mois selon T°. Idéal pour réduire fréquence d\'apport. Compatible arrosage automatique.',
      isActive: true,
      createdBy: ADMIN,
    },
    {
      code: 'PP-006',
      productType: 'insecticide',
      commercialName: 'Karate Zeon 50 CS',
      approvalNumber: 'AMM-2016-0073',
      activeIngredient: 'Lambda-cyhalothrine 50 g/L',
      formulation: 'Suspension de capsules (CS)',
      concentration: '50 g/L',
      usageDose: '0,5 mL/L d\'eau',
      targetPests: 'Chenilles défoliatrices, charançons, punaises, sauterelles',
      targetCrop: 'Arbres et arbustes ornementaux, gazons, haies',
      reEntryDelay: '24 heures',
      technicalDocs: 'Syngenta.',
      packaging: 'Flacon 100 mL, Bidon 500 mL',
      toxicologicalClass: 'Attention — GHS07/GHS09',
      ppe: 'Gants, combinaison, masque A1, lunettes.',
      storageConditions: '5–30 °C, à l\'abri du gel et de la chaleur.',
      preUseInstructions: 'Agiter bien avant usage. Préparer la solution juste avant application.',
      duringUseInstructions: 'Application foliaire en soirée pour protéger les pollinisateurs.',
      wasteDisposal: 'Triple rinçage emballages. Filière collecte spécialisée.',
      notes: 'Pyréthrïnoïde de synthèse. Actif par contact et ingestion. Rémanence 7–14 jours.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'PP-007',
      productType: 'fongicide',
      commercialName: 'Topas 100 EC',
      approvalNumber: 'AMM-2015-0099',
      activeIngredient: 'Penconazole 100 g/L',
      formulation: 'Concentré émulsifiable (EC)',
      concentration: '100 g/L',
      usageDose: '0,5 mL/L d\'eau',
      targetPests: 'Oïdium, maladies cryptogamiques',
      targetCrop: 'Rosiers, cucurbitacées ornementales, arbustes',
      reEntryDelay: '24 heures',
      technicalDocs: 'Syngenta — homologué cultures ornementales.',
      packaging: 'Flacon 100 mL',
      toxicologicalClass: 'Danger — GHS08',
      ppe: 'Gants, lunettes, masque demi-visage.',
      storageConditions: '5–30 °C, loin de sources de chaleur.',
      preUseInstructions: 'Préférer application préventive en début de pousse.',
      duringUseInstructions: 'Alterner avec d\'autres modes d\'action. Max 3 applications/saison.',
      wasteDisposal: 'Triple rinçage. Collecte déchets phyto.',
      notes: 'Triazole systémique. Excellente pénétration foliaire. Usage curatif et préventif.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'PP-008',
      productType: 'engrais',
      commercialName: 'Hydrocomplex 12-11-18',
      approvalNumber: null,
      activeIngredient: 'NPK 12-11-18 + MgO + oligo-éléments',
      formulation: 'Granulés solubles',
      concentration: 'NPK 12-11-18 + 2,7 MgO',
      usageDose: '2–3 g/L en fertigation / 30–40 g/m² en surface',
      targetPests: null,
      targetCrop: 'Arbres, arbustes, gazons, massifs fleuris',
      reEntryDelay: 'Aucun',
      technicalDocs: 'Yara — fiche technique disponible.',
      packaging: 'Sac 2 kg, Sac 25 kg',
      toxicologicalClass: 'Non classé',
      ppe: 'Gants de jardinage recommandés.',
      storageConditions: 'Local sec, 5–35 °C. Fermer le sac après usage.',
      preUseInstructions: 'Dissoudre dans l\'eau pour fertigation. Agiter jusqu\'à dissolution complète.',
      duringUseInstructions: 'Ne pas épandre sur feuillage mouillé en plein soleil (risque de brûlure).',
      wasteDisposal: 'Emballages vides en ordures ménagères. Produit soluble non dangereux.',
      notes: 'Engrais complet équilibré. Convient pour fertigation goutte-à-goutte. Riche en potassium pour qualité floraison.',
      isActive: true,
      createdBy: ADMIN,
    },
    {
      code: 'PP-009',
      productType: 'herbicide',
      commercialName: 'Devrinol 45 FL',
      approvalNumber: 'AMM-2019-0201',
      activeIngredient: 'Naptalam 45 %',
      formulation: 'Suspension concentrée (SC)',
      concentration: '45 %',
      usageDose: '8 mL/L d\'eau',
      targetPests: 'Graminées annuelles, mauvaises herbes en pré-levée',
      targetCrop: 'Massifs ornementaux établis, pieds d\'arbustes',
      reEntryDelay: 'Après séchage du produit',
      technicalDocs: 'UCB — fiche sécurité disponible.',
      packaging: 'Bidon 1 L',
      toxicologicalClass: 'Attention — GHS07',
      ppe: 'Gants, combinaison, lunettes de protection.',
      storageConditions: 'À l\'abri du gel et de la chaleur > 40 °C.',
      preUseInstructions: 'Appliquer en pré-levée des adventices. Arroser légèrement après application.',
      duringUseInstructions: 'Éviter contact avec feuillage des plantes cultivées.',
      wasteDisposal: 'Triple rinçage des bidons. Collecte déchets phytosanitaires agréée.',
      notes: 'Herbicide de sol résiduel. Efficace 6–8 semaines. À utiliser avant germination des mauvaises herbes.',
      isActive: true,
      createdBy: KARIM,
    },
    {
      code: 'PP-010',
      productType: 'autre',
      commercialName: 'Bouillie Bordelaise RSR',
      approvalNumber: null,
      activeIngredient: 'Sulfate de cuivre tribasique 20 %',
      formulation: 'Poudre mouillable (WP)',
      concentration: '20 % cuivre métal',
      usageDose: '20 g/L d\'eau',
      targetPests: 'Mildiou, bactérioses, maladies cryptogamiques à large spectre',
      targetCrop: 'Toutes plantes ornementales, arbres fruitiers, potagers',
      reEntryDelay: '24 heures',
      technicalDocs: 'Produit de biocontrôle — usage possible en agriculture biologique.',
      packaging: 'Sachet 150 g, Boîte 1 kg',
      toxicologicalClass: 'Attention — GHS09 (dangereux milieu aquatique)',
      ppe: 'Gants, lunettes, masque poussières.',
      storageConditions: '5–30 °C, local sec, récipient fermé.',
      preUseInstructions: 'Dissoudre la poudre dans un peu d\'eau avant d\'ajouter le volume final. Agiter régulièrement pendant usage.',
      duringUseInstructions: 'Ne pas utiliser sur feuillage jeune sensible ou par fortes chaleurs.',
      wasteDisposal: 'Triple rinçage emballages. Collecte déchets phyto — ne pas rejeter en milieu aquatique.',
      notes: 'Fongicide-bactéricide de contact classique. Utilisé en préventif ou au stade initial d\'infestation.',
      isActive: true,
      createdBy: ADMIN,
    },
  ]).onConflictDoNothing()

  console.log('  ✓ 10 produits phytosanitaires insérés')
  console.log('Done.')
}

main()
  .then(() => process.exit(0))
  .catch((e) => { console.error(e); process.exit(1) })
