export type Project = {
  slug: string
  name: string
  category: 'Villa' | 'Résidence' | 'Hôtel' | 'Entreprise' | 'Restauration'
  location: string
  description: string
  quote: string
  images: string[]
}

export const projects: Project[] = [
  {
    slug: 'villa-notre-dame',
    name: 'Villa Notre-Dame',
    category: 'Villa',
    location: 'Tunisie',
    quote: 'Le jardin, la pièce la plus vivante et indispensable de la maison.',
    description:
      "Un espace paysager d'exception où la beauté de l'olivier centenaire, le mouvement délicat des végétaux et le tapis d'herbe forment un tableau vivant. SOPAT a assuré la conception, la réalisation et l'entretien de ce jardin qui prolonge élégamment l'architecture de la villa.",
    images: [
      '/projects/villa-notre-dame/1-6.jpg',
      '/projects/villa-notre-dame/4-copy-1.jpg',
      '/projects/villa-notre-dame/5-copy-1.jpg',
      '/projects/villa-notre-dame/6-copy-1.jpg',
      '/projects/villa-notre-dame/7-copy.jpg',
      '/projects/villa-notre-dame/8-copy-1.jpg',
      '/projects/villa-notre-dame/9-copy.jpg',
    ],
  },
  {
    slug: 'villa-marsa',
    name: 'Villa Marsa',
    category: 'Villa',
    location: 'La Marsa, Tunisie',
    quote: 'Un havre de verdure et d\'élégance, où luxe et bien-être se rencontrent.',
    description:
      "Le jardin moderne comme extension naturelle de la maison. Ce projet intègre les tendances décoratives contemporaines pour créer un espace extérieur raffiné, pensé comme un véritable salon à ciel ouvert où luxe et bien-être se conjuguent harmonieusement.",
    images: [
      '/projects/villa-marsa/MVS_2950.jpg',
      '/projects/villa-marsa/MVS_2952.jpg',
      '/projects/villa-marsa/MVS_2953.jpg',
      '/projects/villa-marsa/MVS_2956.jpg',
      '/projects/villa-marsa/MVS_2959.jpg',
      '/projects/villa-marsa/MVS_2960.jpg',
      '/projects/villa-marsa/MVS_2967.jpg',
      '/projects/villa-marsa/MVS_2973.jpg',
      '/projects/villa-marsa/MVS_2999.jpg',
    ],
  },
  {
    slug: 'villa-manar',
    name: 'Villa Manar',
    category: 'Villa',
    location: 'Tunisie',
    quote: 'Les jardins sont devenus des pièces à part entière au sein des maisons.',
    description:
      "Conception paysagère contemporaine où le jardin s'impose comme une pièce à part entière. Ce projet marie luxe design et bien-être pour créer une retraite élégante et paisible, suivant les tendances décoratives les plus actuelles.",
    images: [
      '/projects/villa-manar/1-5.jpg',
      '/projects/villa-manar/2-5.jpg',
      '/projects/villa-manar/3-5.jpg',
      '/projects/villa-manar/4-4.jpg',
      '/projects/villa-manar/5-4.jpg',
      '/projects/villa-manar/6-4.jpg',
      '/projects/villa-manar/7-4.jpg',
      '/projects/villa-manar/10-4.jpg',
      '/projects/villa-manar/11-4.jpg',
    ],
  },
  {
    slug: 'villa-jardins-de-carthage',
    name: 'Villa Jardins de Carthage',
    category: 'Villa',
    location: 'Carthage, Tunisie',
    quote: 'Des espaces de vie lumineux et colorés, aux volumes variés et aux textures multiples.',
    description:
      "Une villa de maître aux jardins raffinés et luxuriants. La richesse des volumes et la diversité des textures créent des espaces de vie lumineux et colorés, témoignant de l'engagement de SOPAT pour un paysagisme d'excellence.",
    images: [
      '/projects/villa-jardins-de-carthage/MVS_4094.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4097.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4102.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4106.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4119.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4121.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4153.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4164.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4169.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4176.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4180.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4191.jpg',
    ],
  },
  {
    slug: 'villa-jardin-del-manzeh',
    name: 'Villa Jardin del Manzeh',
    category: 'Villa',
    location: 'El Menzah, Tunisie',
    quote: 'Une palette végétale exotique et graphique pour une villa contemporaine sur les hauteurs.',
    description:
      "Villa contemporaine à deux niveaux sur un terrain en pente à El Menzah. Une palette végétale exotique et graphique — Cactus, Dasylirions, Yuccas, Arecastrum, Cycas dion, Alocasia — habille ce jardin de caractère, alliant modernité et audace botanique.",
    images: [
      '/projects/villa-jardin-del-manzeh/01.jpg',
      '/projects/villa-jardin-del-manzeh/02.jpg',
      '/projects/villa-jardin-del-manzeh/03.jpg',
      '/projects/villa-jardin-del-manzeh/04.jpg',
      '/projects/villa-jardin-del-manzeh/05.jpg',
      '/projects/villa-jardin-del-manzeh/06.jpg',
      '/projects/villa-jardin-del-manzeh/07.jpg',
      '/projects/villa-jardin-del-manzeh/08.jpg',
      '/projects/villa-jardin-del-manzeh/09.jpg',
      '/projects/villa-jardin-del-manzeh/10-3.jpg',
      '/projects/villa-jardin-del-manzeh/11-3.jpg',
      '/projects/villa-jardin-del-manzeh/12-3.jpg',
    ],
  },
  {
    slug: 'villa-carthage',
    name: 'Villa Carthage',
    category: 'Villa',
    location: 'Carthage, Tunisie',
    quote: 'Mouvement, fluidité et élégance — pleinement exprimés au sein des espaces verts.',
    description:
      "Un espace paysager où mouvement, fluidité et élégance s'expriment pleinement. Conçu et réalisé par SOPAT, ce jardin de villa incarne la vision d'un paysagisme vivant et sensible, en parfaite résonance avec l'architecture environnante.",
    images: [
      '/projects/villa-carthage/1-4.jpg',
      '/projects/villa-carthage/2-4.jpg',
      '/projects/villa-carthage/3-4.jpg',
      '/projects/villa-carthage/4-3.jpg',
      '/projects/villa-carthage/5-3.jpg',
      '/projects/villa-carthage/6-3.jpg',
      '/projects/villa-carthage/7-3.jpg',
      '/projects/villa-carthage/8-3.jpg',
      '/projects/villa-carthage/9-2.jpg',
      '/projects/villa-carthage/10-2.jpg',
      '/projects/villa-carthage/11-2.jpg',
      '/projects/villa-carthage/12-2.jpg',
      '/projects/villa-carthage/17.jpg',
    ],
  },
  {
    slug: 'the-residence',
    name: 'The Residence',
    category: 'Résidence',
    location: 'Hammamet, Tunisie',
    quote: 'Qui plante un jardin plante le bonheur.',
    description:
      "Au cœur de Hammamet, SOPAT s'est engagé à créer le bonheur dans cette résidence. Un projet porteur d'une mission profonde : faire du cadre de vie un espace de sérénité et de beauté, où chaque résident trouve son propre havre de paix.",
    images: [
      '/projects/the-residence/1-3.jpg',
      '/projects/the-residence/2-3.jpg',
      '/projects/the-residence/3-3.jpg',
      '/projects/the-residence/4-2.jpg',
      '/projects/the-residence/5-2.jpg',
      '/projects/the-residence/6-2.jpg',
      '/projects/the-residence/7-2.jpg',
      '/projects/the-residence/8-2.jpg',
      '/projects/the-residence/9-1.jpg',
      '/projects/the-residence/10-1.jpg',
      '/projects/the-residence/11-1.jpg',
      '/projects/the-residence/12-1.jpg',
      '/projects/the-residence/13-1.jpg',
    ],
  },
  {
    slug: 'residence-lac-2',
    name: 'Résidence Lac 2',
    category: 'Résidence',
    location: 'Lac 2, Tunis',
    quote: 'Les jardins suspendus invitent la nature dans le décor pour une atmosphère originale et poétique.',
    description:
      "Faire entrer la nature dans l'appartement à travers des jardins suspendus. Ce projet explore la végétalisation verticale et suspendue pour apporter une atmosphère originale et poétique à un cadre de vie urbain, transformant chaque balcon en jardin aérien.",
    images: [
      '/projects/residence-lac-2/MVS_1690.jpg',
      '/projects/residence-lac-2/MVS_1697.jpg',
      '/projects/residence-lac-2/MVS_1698.jpg',
      '/projects/residence-lac-2/MVS_1699.jpg',
      '/projects/residence-lac-2/MVS_1703.jpg',
      '/projects/residence-lac-2/MVS_1705.jpg',
      '/projects/residence-lac-2/MVS_1706.jpg',
      '/projects/residence-lac-2/MVS_1707.jpg',
      '/projects/residence-lac-2/MVS_1714.jpg',
      '/projects/residence-lac-2/MVS_1715.jpg',
    ],
  },
  {
    slug: 'residence-la-douce-lac',
    name: 'Résidence La Douce Lac',
    category: 'Résidence',
    location: 'Lac, Tunis',
    quote: 'Structure géométrique, caractère raffiné et sobre — un jardin contemporain d\'exception.',
    description:
      "Un jardin contemporain alliant structure géométrique et caractère raffiné. Conçu pour répondre aux désirs d'évasion en milieu urbain, ce projet mêle esthétique moderne et élégance sobre, offrant un refuge serein au cœur de la ville.",
    images: [
      '/projects/residence-la-douce-lac/MVS_2883.jpg',
      '/projects/residence-la-douce-lac/MVS_2886.jpg',
      '/projects/residence-la-douce-lac/MVS_2888.jpg',
      '/projects/residence-la-douce-lac/MVS_2891.jpg',
      '/projects/residence-la-douce-lac/MVS_2893.jpg',
      '/projects/residence-la-douce-lac/MVS_2895.jpg',
      '/projects/residence-la-douce-lac/MVS_2899.jpg',
      '/projects/residence-la-douce-lac/MVS_2900.jpg',
      '/projects/residence-la-douce-lac/MVS_2910.jpg',
      '/projects/residence-la-douce-lac/MVS_2917.jpg',
    ],
  },
  {
    slug: 'novotel-tunis-lac',
    name: 'Novotel Tunis Lac',
    category: 'Hôtel',
    location: 'Lac, Tunis',
    quote: 'Un jardin 100% méditerranéen, des intérieurs végétalisés, des terrasses suspendues.',
    description:
      "Première expérience de SOPAT dans la conception de jardins sur toiture-terrasse. Ce projet hôtelier méditerranéen intègre des murs verts naturels en intérieur, des terrasses suspendues et un jardin extérieur luxuriant, ajoutant une valeur inestimable au secteur du tourisme tunisien.",
    images: [
      '/projects/novotel-tunis-lac/1-2.jpg',
      '/projects/novotel-tunis-lac/2-2.jpg',
      '/projects/novotel-tunis-lac/3-2.jpg',
      '/projects/novotel-tunis-lac/4-1.jpg',
      '/projects/novotel-tunis-lac/5-1.jpg',
      '/projects/novotel-tunis-lac/6-1.jpg',
      '/projects/novotel-tunis-lac/7-1.jpg',
      '/projects/novotel-tunis-lac/8-1.jpg',
      '/projects/novotel-tunis-lac/9.jpg',
      '/projects/novotel-tunis-lac/MVS_6247.jpg',
      '/projects/novotel-tunis-lac/MVS_6252.jpg',
      '/projects/novotel-tunis-lac/MVS_6258.jpg',
      '/projects/novotel-tunis-lac/MVS_6293.jpg',
      '/projects/novotel-tunis-lac/MVS_6295.jpg',
      '/projects/novotel-tunis-lac/MVS_6888.jpg',
      '/projects/novotel-tunis-lac/MVS_6903.jpg',
      '/projects/novotel-tunis-lac/MVS_6905.jpg',
      '/projects/novotel-tunis-lac/MVS_6909.jpg',
      '/projects/novotel-tunis-lac/MVS_6910.jpg',
    ],
  },
  {
    slug: 'hotel-laico-tunis',
    name: 'Hotel Laico Tunis',
    category: 'Hôtel',
    location: 'Tunis',
    quote: 'Le jardin tropical — une architecture végétale entre modernité et tradition.',
    description:
      "Le jardin tropical de l'Hôtel Laico allie architecture contemporaine et éléments traditionnels. Des lignes épurées, un style moderne et une végétation généreuse accessible depuis de multiples angles offrent des vues panoramiques d'une rare qualité paysagère.",
    images: [
      '/projects/hotel-laico-tunis/MVS_7355.jpg',
      '/projects/hotel-laico-tunis/MVS_7363.jpg',
      '/projects/hotel-laico-tunis/MVS_7371.jpg',
      '/projects/hotel-laico-tunis/MVS_7378.jpg',
      '/projects/hotel-laico-tunis/MVS_7383.jpg',
      '/projects/hotel-laico-tunis/MVS_7391.jpg',
      '/projects/hotel-laico-tunis/MVS_7396.jpg',
      '/projects/hotel-laico-tunis/MVS_7401.jpg',
      '/projects/hotel-laico-tunis/MVS_7419.jpg',
    ],
  },
  {
    slug: 'the-orangers',
    name: 'The Orangers Garden Villas',
    category: 'Hôtel',
    location: 'Nabeul, Tunisie',
    quote: 'Cinq hectares d\'orangers, de jasmin et de palmiers au bord de la Méditerranée.',
    description:
      "Resort de luxe 5 étoiles sur les plages méditerranéennes de Nabeul. Cinq hectares de végétation exubérante — orangers, jasmin, palmiers, bougainvilliers, lavande, oliviers et Cycas revolutas — composent un paysage d'une richesse botanique exceptionnelle.",
    images: [
      '/projects/the-orangers/MVS_7702.jpg',
      '/projects/the-orangers/MVS_7705.jpg',
      '/projects/the-orangers/MVS_7706.jpg',
      '/projects/the-orangers/MVS_7711.jpg',
      '/projects/the-orangers/MVS_7712.jpg',
      '/projects/the-orangers/MVS_7720.jpg',
      '/projects/the-orangers/MVS_7723.jpg',
      '/projects/the-orangers/MVS_7725.jpg',
      '/projects/the-orangers/MVS_7727.jpg',
      '/projects/the-orangers/MVS_7728.jpg',
      '/projects/the-orangers/MVS_7730.jpg',
      '/projects/the-orangers/MVS_7731.jpg',
      '/projects/the-orangers/MVS_7734.jpg',
      '/projects/the-orangers/MVS_7739.jpg',
      '/projects/the-orangers/MVS_7743.jpg',
      '/projects/the-orangers/MVS_7744.jpg',
      '/projects/the-orangers/MVS_7748.jpg',
      '/projects/the-orangers/MVS_7749.jpg',
      '/projects/the-orangers/MVS_7752.jpg',
      '/projects/the-orangers/MVS_7753.jpg',
      '/projects/the-orangers/MVS_7754.jpg',
    ],
  },
  {
    slug: 'hotel-movenpick',
    name: 'Hôtel Mövenpick Lac',
    category: 'Hôtel',
    location: 'Lac 1, Tunis',
    quote: 'Un charme intemporel préservé grâce à un engagement indéfectible pour le développement durable.',
    description:
      "Réalisé il y a plus de 3 ans, ce projet hôtelier conserve tout son charme et sa beauté. SOPAT s'engage pour un développement durable garantissant que chaque réalisation perdure en parfait état, grâce à des équipes terrain dédiées et une végétation florissante.",
    images: [
      '/projects/hotel-movenpick/MVS_2082.jpg',
      '/projects/hotel-movenpick/MVS_4621.jpg',
      '/projects/hotel-movenpick/MVS_4629.jpg',
      '/projects/hotel-movenpick/MVS_4660.jpg',
      '/projects/hotel-movenpick/MVS_4674.jpg',
      '/projects/hotel-movenpick/MVS_4692.jpg',
      '/projects/hotel-movenpick/MVS_4699.jpg',
      '/projects/hotel-movenpick/MVS_4723.jpg',
      '/projects/hotel-movenpick/MVS_4724.jpg',
      '/projects/hotel-movenpick/MVS_4726.jpg',
      '/projects/hotel-movenpick/MVS_4729.jpg',
      '/projects/hotel-movenpick/MVS_4730.jpg',
      '/projects/hotel-movenpick/MVS_4733.jpg',
      '/projects/hotel-movenpick/MVS_4742.jpg',
      '/projects/hotel-movenpick/MVS_4755.jpg',
      '/projects/hotel-movenpick/MVS_4758.jpg',
      '/projects/hotel-movenpick/MVS_4761.jpg',
    ],
  },
  {
    slug: 'gat',
    name: 'GAT Assurances',
    category: 'Entreprise',
    location: 'Tunis',
    quote: 'Travailler avec vue sur un jardin — le bien-être au cœur de l\'espace professionnel.',
    description:
      "Jardin corporate créé pour le siège de GAT Assurances. La présence de plantes et de verdure réduit le stress des collaborateurs et améliore leur humeur au quotidien. Un investissement dans le bien-être qui se traduit directement en productivité et en créativité.",
    images: [
      '/projects/gat/1-1.jpg',
      '/projects/gat/2-1.jpg',
      '/projects/gat/3-1.jpg',
      '/projects/gat/4.jpg',
      '/projects/gat/5.jpg',
      '/projects/gat/6.jpg',
      '/projects/gat/7.jpg',
      '/projects/gat/8.jpg',
    ],
  },
  {
    slug: 'gourmandise-lac',
    name: 'Maison Gourmandise',
    category: 'Restauration',
    location: 'Lac 1, Tunis',
    quote: 'Un espace sublime, conçu avec gratitude pour un client fidèle et partenaire de longue date.',
    description:
      "SOPAT exprime sa fierté d'avoir conçu et aménagé cet espace pour Maison Gourmandise, client fidèle et partenaire de confiance. Un projet de restauration où l'art du paysage rencontre l'art de recevoir, pour une expérience sensorielle complète.",
    images: [
      '/projects/gourmandise-lac/1.jpg',
      '/projects/gourmandise-lac/2.jpg',
      '/projects/gourmandise-lac/3.jpg',
      '/projects/gourmandise-lac/MVS_2562.jpg',
      '/projects/gourmandise-lac/MVS_2567.jpg',
      '/projects/gourmandise-lac/MVS_2569.jpg',
      '/projects/gourmandise-lac/MVS_2570.jpg',
    ],
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}

export function getAdjacentProjects(slug: string): { prev: Project | null; next: Project | null } {
  const index = projects.findIndex((p) => p.slug === slug)
  return {
    prev: index > 0 ? projects[index - 1] : null,
    next: index < projects.length - 1 ? projects[index + 1] : null,
  }
}
