export type Project = {
  slug: string
  name: string
  category: 'Villa' | 'Résidence' | 'Hôtel' | 'Entreprise' | 'Restauration'
  location: string
  description: string
  quote: string
  images: string[]
}

export const projects: Project[] = [
  // ─── Réalisations 2024 ───────────────────────────────────────────────────────
  {
    slug: 'hotel-one-resort',
    name: 'Hôtel One Resort',
    category: 'Hôtel',
    location: 'Monastir, Tunisie',
    quote: 'Des jardins qui prolongent l\'expérience du séjour, du hall aux rivages.',
    description:
      "Aménagement paysager complet d'un resort balnéaire : palmeraies, massifs fleuris et pelouses impeccables composent un parcours végétal continu entre les espaces de vie de l'hôtel. SOPAT assure la conception, la réalisation et l'entretien de l'ensemble des espaces verts.",
    images: [
      '/projects/hotel-one-resort/1.jpg',
      '/projects/hotel-one-resort/2.jpg',
      '/projects/hotel-one-resort/3.jpg',
      '/projects/hotel-one-resort/4.jpg',
      '/projects/hotel-one-resort/5.jpg',
      '/projects/hotel-one-resort/6.jpg',
      '/projects/hotel-one-resort/7.jpg',
      '/projects/hotel-one-resort/8.jpg',
    ],
  },
  {
    slug: 'hotel-hammamet-2024',
    name: 'Hôtel Hammamet',
    category: 'Hôtel',
    location: 'Hammamet, Tunisie',
    quote: 'L\'hospitalité commence au jardin.',
    description:
      "Requalification paysagère d'un établissement hôtelier à Hammamet : allées ombragées, palmiers et compositions méditerranéennes accueillent les visiteurs dès l'entrée. Un entretien régulier garantit une qualité constante tout au long de l'année.",
    images: [
      '/projects/hotel-hammamet-2024/1.jpg',
      '/projects/hotel-hammamet-2024/2.jpg',
      '/projects/hotel-hammamet-2024/3.jpg',
      '/projects/hotel-hammamet-2024/4.jpg',
      '/projects/hotel-hammamet-2024/5.jpg',
      '/projects/hotel-hammamet-2024/6.jpg',
      '/projects/hotel-hammamet-2024/7.jpg',
      '/projects/hotel-hammamet-2024/8.jpg',
    ],
  },
  {
    slug: 'hotel-radisson',
    name: 'Hôtel Radisson',
    category: 'Hôtel',
    location: 'Tunisie',
    quote: 'Un standard international, une signature végétale locale.',
    description:
      "Pour cet hôtel d'enseigne internationale, SOPAT a composé des espaces verts à la hauteur des standards de la marque : structure végétale soignée, palette méditerranéenne et finitions impeccables des abords à la piscine.",
    images: [
      '/projects/hotel-radisson/1.jpg',
      '/projects/hotel-radisson/2.jpg',
      '/projects/hotel-radisson/3.jpg',
      '/projects/hotel-radisson/4.jpg',
      '/projects/hotel-radisson/5.jpg',
      '/projects/hotel-radisson/6.jpg',
      '/projects/hotel-radisson/7.jpg',
      '/projects/hotel-radisson/8.jpg',
    ],
  },
  {
    slug: 'hotel-novotel',
    name: 'Hôtel Novotel',
    category: 'Hôtel',
    location: 'Tunis, Tunisie',
    quote: 'La nature en ville, au service des voyageurs.',
    description:
      "Aménagement et entretien des espaces extérieurs du Novotel : un écrin de verdure urbain qui adoucit l'architecture contemporaine de l'hôtel et offre aux voyageurs une respiration végétale au cœur de la ville.",
    images: [
      '/projects/hotel-novotel/1.jpg',
      '/projects/hotel-novotel/2.jpg',
      '/projects/hotel-novotel/3.jpg',
      '/projects/hotel-novotel/4.jpg',
      '/projects/hotel-novotel/5.jpg',
      '/projects/hotel-novotel/6.jpg',
      '/projects/hotel-novotel/7.jpg',
      '/projects/hotel-novotel/8.jpg',
    ],
  },
  {
    slug: 'residence-diar-yasmine',
    name: 'Diar Yasmine Plage',
    category: 'Résidence',
    location: 'Tazarka, Tunisie',
    quote: 'Un partenariat durable, un littoral préservé.',
    description:
      "Partenaire RSE de SOPAT, la résidence Diar Yasmine Plage bénéficie d'un aménagement paysager pensé pour le bord de mer : essences résistantes aux embruns, ombrages naturels et espaces communs verdoyants pour les résidents.",
    images: [
      '/projects/residence-diar-yasmine/1.jpg',
      '/projects/residence-diar-yasmine/2.jpg',
      '/projects/residence-diar-yasmine/3.jpg',
      '/projects/residence-diar-yasmine/4.jpg',
      '/projects/residence-diar-yasmine/5.jpg',
      '/projects/residence-diar-yasmine/6.jpg',
      '/projects/residence-diar-yasmine/7.jpg',
      '/projects/residence-diar-yasmine/8.jpg',
    ],
  },
  {
    slug: 'piscine-belvedere',
    name: 'Piscine Belvédère',
    category: 'Résidence',
    location: 'Tunis, Tunisie',
    quote: 'L\'eau et le végétal, un dialogue permanent.',
    description:
      "Autour du bassin, SOPAT a orchestré un paysage où minéral, eau et végétal se répondent : plages engazonnées, massifs graphiques et palmiers structurent un espace de détente aux allures de resort privé.",
    images: [
      '/projects/piscine-belvedere/1.jpg',
      '/projects/piscine-belvedere/2.jpg',
      '/projects/piscine-belvedere/3.jpg',
      '/projects/piscine-belvedere/4.jpg',
      '/projects/piscine-belvedere/5.jpg',
      '/projects/piscine-belvedere/6.jpg',
      '/projects/piscine-belvedere/7.jpg',
      '/projects/piscine-belvedere/8.jpg',
    ],
  },
  {
    slug: 'banque-bte-2024',
    name: 'Banque BTE',
    category: 'Entreprise',
    location: 'Tunis, Tunisie',
    quote: 'Le végétal comme signature institutionnelle.',
    description:
      "Aménagement paysager du siège de la BTE : compositions structurées et entretien de haute précision confèrent aux abords de la banque une image institutionnelle soignée, à la mesure de l'établissement.",
    images: [
      '/projects/banque-bte-2024/1.jpg',
      '/projects/banque-bte-2024/2.jpg',
      '/projects/banque-bte-2024/3.jpg',
      '/projects/banque-bte-2024/4.jpg',
      '/projects/banque-bte-2024/5.jpg',
      '/projects/banque-bte-2024/6.jpg',
      '/projects/banque-bte-2024/7.jpg',
      '/projects/banque-bte-2024/8.jpg',
    ],
  },
  {
    slug: 'villa-sidi-abdelaziz',
    name: 'Villa Sidi Abdelaziz',
    category: 'Villa',
    location: 'La Marsa, Tunisie',
    quote: 'Un jardin de bord de mer, entre lumière et fraîcheur.',
    description:
      "Dans ce quartier emblématique de La Marsa, SOPAT a dessiné un jardin qui capte la lumière marine : pelouses généreuses, essences méditerranéennes et coins d'ombre composent un art de vivre en plein air.",
    images: [
      '/projects/villa-sidi-abdelaziz/1.jpg',
      '/projects/villa-sidi-abdelaziz/2.jpg',
      '/projects/villa-sidi-abdelaziz/3.jpg',
      '/projects/villa-sidi-abdelaziz/4.jpg',
      '/projects/villa-sidi-abdelaziz/5.jpg',
      '/projects/villa-sidi-abdelaziz/6.jpg',
      '/projects/villa-sidi-abdelaziz/7.jpg',
      '/projects/villa-sidi-abdelaziz/8.jpg',
    ],
  },
  {
    slug: 'villa-korba',
    name: 'Villa Korba',
    category: 'Villa',
    location: 'Korba, Tunisie',
    quote: 'La douceur du Cap Bon, cultivée au jardin.',
    description:
      "Un jardin familial au cœur du Cap Bon : SOPAT y a marié vergers, massifs fleuris et espaces de vie extérieurs pour prolonger la maison dans un paysage généreux et vivant, fidèle à l'esprit de la région.",
    images: [
      '/projects/villa-korba/1.jpg',
      '/projects/villa-korba/2.jpg',
      '/projects/villa-korba/3.jpg',
      '/projects/villa-korba/4.jpg',
      '/projects/villa-korba/5.jpg',
      '/projects/villa-korba/6.jpg',
      '/projects/villa-korba/7.jpg',
      '/projects/villa-korba/8.jpg',
    ],
  },
  {
    slug: 'villa-beni-khiar',
    name: 'Villa Beni Khiar',
    category: 'Villa',
    location: 'Beni Khiar, Tunisie',
    quote: 'Chaque parcelle a son caractère ; le jardin le révèle.',
    description:
      "Conception et réalisation d'un jardin contemporain à Beni Khiar : lignes épurées, gazon sculpté et palette végétale choisie pour la douceur du climat côtier du Cap Bon.",
    images: [
      '/projects/villa-beni-khiar/1.jpg',
      '/projects/villa-beni-khiar/2.jpg',
      '/projects/villa-beni-khiar/3.jpg',
      '/projects/villa-beni-khiar/4.jpg',
      '/projects/villa-beni-khiar/5.jpg',
      '/projects/villa-beni-khiar/6.jpg',
      '/projects/villa-beni-khiar/7.jpg',
      '/projects/villa-beni-khiar/8.jpg',
    ],
  },
  {
    slug: 'villa-lac-2',
    name: 'Villa Lac 2',
    category: 'Villa',
    location: 'Les Berges du Lac 2, Tunis',
    quote: 'Un écrin contemporain pour une architecture d\'exception.',
    description:
      "Aux Berges du Lac 2, SOPAT a composé un jardin à l'image de l'architecture qu'il accompagne : graphique, précis et luxuriant. Terrasses végétalisées et massifs structurés dessinent un cadre de vie contemporain.",
    images: [
      '/projects/villa-lac-2/1.jpg',
      '/projects/villa-lac-2/2.jpg',
      '/projects/villa-lac-2/3.jpg',
      '/projects/villa-lac-2/4.jpg',
      '/projects/villa-lac-2/5.jpg',
      '/projects/villa-lac-2/6.jpg',
      '/projects/villa-lac-2/7.jpg',
      '/projects/villa-lac-2/8.jpg',
    ],
  },
  {
    slug: 'villa-choutrana',
    name: 'Villa Choutrana',
    category: 'Villa',
    location: 'La Soukra, Tunisie',
    quote: 'Le luxe discret d\'un jardin bien pensé.',
    description:
      "Réalisation d'un jardin résidentiel à Choutrana : pelouses denses, haies structurantes et touches fleuries composent un extérieur élégant et facile à vivre, entretenu par les équipes SOPAT.",
    images: [
      '/projects/villa-choutrana/1.jpg',
      '/projects/villa-choutrana/2.jpg',
      '/projects/villa-choutrana/3.jpg',
      '/projects/villa-choutrana/4.jpg',
      '/projects/villa-choutrana/5.jpg',
      '/projects/villa-choutrana/6.jpg',
      '/projects/villa-choutrana/7.jpg',
      '/projects/villa-choutrana/8.jpg',
    ],
  },
  {
    slug: 'villa-jabas',
    name: 'Villa Jabas',
    category: 'Villa',
    location: 'Tunisie',
    quote: 'Un jardin qui grandit avec la maison.',
    description:
      "De la conception à l'entretien, SOPAT accompagne la Villa Jabas dans la durée : un jardin évolutif où arbres d'ombrage, gazon et vivaces gagnent en caractère saison après saison.",
    images: [
      '/projects/villa-jabas/1.jpg',
      '/projects/villa-jabas/2.jpg',
      '/projects/villa-jabas/3.jpg',
      '/projects/villa-jabas/4.jpg',
      '/projects/villa-jabas/5.jpg',
      '/projects/villa-jabas/6.jpg',
      '/projects/villa-jabas/7.jpg',
      '/projects/villa-jabas/8.jpg',
    ],
  },
  // ─── Réalisations antérieures ────────────────────────────────────────────────
  {
    slug: 'villa-notre-dame',
    name: 'Villa Notre-Dame',
    category: 'Villa',
    location: 'Tunisie',
    quote: 'Le jardin, la pièce la plus vivante et indispensable de la maison.',
    description:
      "Un espace paysager d'exception où la beauté de l'olivier centenaire, le mouvement délicat des végétaux et le tapis d'herbe forment un tableau vivant. SOPAT a assuré la conception, la réalisation et l'entretien de ce jardin qui prolonge élégamment l'architecture de la villa.",
    images: [
      '/projects/villa-notre-dame/1-6.jpg',
      '/projects/villa-notre-dame/4-copy-1.jpg',
      '/projects/villa-notre-dame/5-copy-1.jpg',
      '/projects/villa-notre-dame/6-copy-1.jpg',
      '/projects/villa-notre-dame/7-copy.jpg',
      '/projects/villa-notre-dame/8-copy-1.jpg',
      '/projects/villa-notre-dame/9-copy.jpg',
    ],
  },
  {
    slug: 'villa-marsa',
    name: 'Villa Marsa',
    category: 'Villa',
    location: 'La Marsa, Tunisie',
    quote: 'Un havre de verdure et d\'élégance, où luxe et bien-être se rencontrent.',
    description:
      "Le jardin moderne comme extension naturelle de la maison. Ce projet intègre les tendances décoratives contemporaines pour créer un espace extérieur raffiné, pensé comme un véritable salon à ciel ouvert où luxe et bien-être se conjuguent harmonieusement.",
    images: [
      '/projects/villa-marsa/MVS_2950.jpg',
      '/projects/villa-marsa/MVS_2952.jpg',
      '/projects/villa-marsa/MVS_2953.jpg',
      '/projects/villa-marsa/MVS_2956.jpg',
      '/projects/villa-marsa/MVS_2959.jpg',
      '/projects/villa-marsa/MVS_2960.jpg',
      '/projects/villa-marsa/MVS_2967.jpg',
      '/projects/villa-marsa/MVS_2973.jpg',
      '/projects/villa-marsa/MVS_2999.jpg',
    ],
  },
  {
    slug: 'villa-manar',
    name: 'Villa Manar',
    category: 'Villa',
    location: 'Tunisie',
    quote: 'Les jardins sont devenus des pièces à part entière au sein des maisons.',
    description:
      "Conception paysagère contemporaine où le jardin s'impose comme une pièce à part entière. Ce projet marie luxe design et bien-être pour créer une retraite élégante et paisible, suivant les tendances décoratives les plus actuelles.",
    images: [
      '/projects/villa-manar/1-5.jpg',
      '/projects/villa-manar/2-5.jpg',
      '/projects/villa-manar/3-5.jpg',
      '/projects/villa-manar/4-4.jpg',
      '/projects/villa-manar/5-4.jpg',
      '/projects/villa-manar/6-4.jpg',
      '/projects/villa-manar/7-4.jpg',
      '/projects/villa-manar/10-4.jpg',
      '/projects/villa-manar/11-4.jpg',
    ],
  },
  {
    slug: 'villa-jardins-de-carthage',
    name: 'Villa Jardins de Carthage',
    category: 'Villa',
    location: 'Carthage, Tunisie',
    quote: 'Des espaces de vie lumineux et colorés, aux volumes variés et aux textures multiples.',
    description:
      "Une villa de maître aux jardins raffinés et luxuriants. La richesse des volumes et la diversité des textures créent des espaces de vie lumineux et colorés, témoignant de l'engagement de SOPAT pour un paysagisme d'excellence.",
    images: [
      '/projects/villa-jardins-de-carthage/MVS_4094.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4097.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4102.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4106.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4119.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4121.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4153.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4164.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4169.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4176.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4180.jpg',
      '/projects/villa-jardins-de-carthage/MVS_4191.jpg',
    ],
  },
  {
    slug: 'villa-jardin-del-manzeh',
    name: 'Villa Jardin del Manzeh',
    category: 'Villa',
    location: 'El Menzah, Tunisie',
    quote: 'Une palette végétale exotique et graphique pour une villa contemporaine sur les hauteurs.',
    description:
      "Villa contemporaine à deux niveaux sur un terrain en pente à El Menzah. Une palette végétale exotique et graphique — Cactus, Dasylirions, Yuccas, Arecastrum, Cycas dion, Alocasia — habille ce jardin de caractère, alliant modernité et audace botanique.",
    images: [
      '/projects/villa-jardin-del-manzeh/01.jpg',
      '/projects/villa-jardin-del-manzeh/02.jpg',
      '/projects/villa-jardin-del-manzeh/03.jpg',
      '/projects/villa-jardin-del-manzeh/04.jpg',
      '/projects/villa-jardin-del-manzeh/05.jpg',
      '/projects/villa-jardin-del-manzeh/06.jpg',
      '/projects/villa-jardin-del-manzeh/07.jpg',
      '/projects/villa-jardin-del-manzeh/08.jpg',
      '/projects/villa-jardin-del-manzeh/09.jpg',
      '/projects/villa-jardin-del-manzeh/10-3.jpg',
      '/projects/villa-jardin-del-manzeh/11-3.jpg',
      '/projects/villa-jardin-del-manzeh/12-3.jpg',
    ],
  },
  {
    slug: 'villa-carthage',
    name: 'Villa Carthage',
    category: 'Villa',
    location: 'Carthage, Tunisie',
    quote: 'Mouvement, fluidité et élégance — pleinement exprimés au sein des espaces verts.',
    description:
      "Un espace paysager où mouvement, fluidité et élégance s'expriment pleinement. Conçu et réalisé par SOPAT, ce jardin de villa incarne la vision d'un paysagisme vivant et sensible, en parfaite résonance avec l'architecture environnante.",
    images: [
      '/projects/villa-carthage/1-4.jpg',
      '/projects/villa-carthage/2-4.jpg',
      '/projects/villa-carthage/3-4.jpg',
      '/projects/villa-carthage/4-3.jpg',
      '/projects/villa-carthage/5-3.jpg',
      '/projects/villa-carthage/6-3.jpg',
      '/projects/villa-carthage/7-3.jpg',
      '/projects/villa-carthage/8-3.jpg',
      '/projects/villa-carthage/9-2.jpg',
      '/projects/villa-carthage/10-2.jpg',
      '/projects/villa-carthage/11-2.jpg',
      '/projects/villa-carthage/12-2.jpg',
      '/projects/villa-carthage/17.jpg',
    ],
  },
  {
    slug: 'the-residence',
    name: 'The Residence',
    category: 'Résidence',
    location: 'Hammamet, Tunisie',
    quote: 'Qui plante un jardin plante le bonheur.',
    description:
      "Au cœur de Hammamet, SOPAT s'est engagé à créer le bonheur dans cette résidence. Un projet porteur d'une mission profonde : faire du cadre de vie un espace de sérénité et de beauté, où chaque résident trouve son propre havre de paix.",
    images: [
      '/projects/the-residence/1-3.jpg',
      '/projects/the-residence/2-3.jpg',
      '/projects/the-residence/3-3.jpg',
      '/projects/the-residence/4-2.jpg',
      '/projects/the-residence/5-2.jpg',
      '/projects/the-residence/6-2.jpg',
      '/projects/the-residence/7-2.jpg',
      '/projects/the-residence/8-2.jpg',
      '/projects/the-residence/9-1.jpg',
      '/projects/the-residence/10-1.jpg',
      '/projects/the-residence/11-1.jpg',
      '/projects/the-residence/12-1.jpg',
      '/projects/the-residence/13-1.jpg',
    ],
  },
  {
    slug: 'residence-lac-2',
    name: 'Résidence Lac 2',
    category: 'Résidence',
    location: 'Lac 2, Tunis',
    quote: 'Les jardins suspendus invitent la nature dans le décor pour une atmosphère originale et poétique.',
    description:
      "Faire entrer la nature dans l'appartement à travers des jardins suspendus. Ce projet explore la végétalisation verticale et suspendue pour apporter une atmosphère originale et poétique à un cadre de vie urbain, transformant chaque balcon en jardin aérien.",
    images: [
      '/projects/residence-lac-2/MVS_1690.jpg',
      '/projects/residence-lac-2/MVS_1697.jpg',
      '/projects/residence-lac-2/MVS_1698.jpg',
      '/projects/residence-lac-2/MVS_1699.jpg',
      '/projects/residence-lac-2/MVS_1703.jpg',
      '/projects/residence-lac-2/MVS_1705.jpg',
      '/projects/residence-lac-2/MVS_1706.jpg',
      '/projects/residence-lac-2/MVS_1707.jpg',
      '/projects/residence-lac-2/MVS_1714.jpg',
      '/projects/residence-lac-2/MVS_1715.jpg',
    ],
  },
  {
    slug: 'residence-la-douce-lac',
    name: 'Résidence La Douce Lac',
    category: 'Résidence',
    location: 'Lac, Tunis',
    quote: 'Structure géométrique, caractère raffiné et sobre — un jardin contemporain d\'exception.',
    description:
      "Un jardin contemporain alliant structure géométrique et caractère raffiné. Conçu pour répondre aux désirs d'évasion en milieu urbain, ce projet mêle esthétique moderne et élégance sobre, offrant un refuge serein au cœur de la ville.",
    images: [
      '/projects/residence-la-douce-lac/MVS_2883.jpg',
      '/projects/residence-la-douce-lac/MVS_2886.jpg',
      '/projects/residence-la-douce-lac/MVS_2888.jpg',
      '/projects/residence-la-douce-lac/MVS_2891.jpg',
      '/projects/residence-la-douce-lac/MVS_2893.jpg',
      '/projects/residence-la-douce-lac/MVS_2895.jpg',
      '/projects/residence-la-douce-lac/MVS_2899.jpg',
      '/projects/residence-la-douce-lac/MVS_2900.jpg',
      '/projects/residence-la-douce-lac/MVS_2910.jpg',
      '/projects/residence-la-douce-lac/MVS_2917.jpg',
    ],
  },
  {
    slug: 'novotel-tunis-lac',
    name: 'Novotel Tunis Lac',
    category: 'Hôtel',
    location: 'Lac, Tunis',
    quote: 'Un jardin 100% méditerranéen, des intérieurs végétalisés, des terrasses suspendues.',
    description:
      "Première expérience de SOPAT dans la conception de jardins sur toiture-terrasse. Ce projet hôtelier méditerranéen intègre des murs verts naturels en intérieur, des terrasses suspendues et un jardin extérieur luxuriant, ajoutant une valeur inestimable au secteur du tourisme tunisien.",
    images: [
      '/projects/novotel-tunis-lac/1-2.jpg',
      '/projects/novotel-tunis-lac/2-2.jpg',
      '/projects/novotel-tunis-lac/3-2.jpg',
      '/projects/novotel-tunis-lac/4-1.jpg',
      '/projects/novotel-tunis-lac/5-1.jpg',
      '/projects/novotel-tunis-lac/6-1.jpg',
      '/projects/novotel-tunis-lac/7-1.jpg',
      '/projects/novotel-tunis-lac/8-1.jpg',
      '/projects/novotel-tunis-lac/9.jpg',
      '/projects/novotel-tunis-lac/MVS_6247.jpg',
      '/projects/novotel-tunis-lac/MVS_6252.jpg',
      '/projects/novotel-tunis-lac/MVS_6258.jpg',
      '/projects/novotel-tunis-lac/MVS_6293.jpg',
      '/projects/novotel-tunis-lac/MVS_6295.jpg',
      '/projects/novotel-tunis-lac/MVS_6888.jpg',
      '/projects/novotel-tunis-lac/MVS_6903.jpg',
      '/projects/novotel-tunis-lac/MVS_6905.jpg',
      '/projects/novotel-tunis-lac/MVS_6909.jpg',
      '/projects/novotel-tunis-lac/MVS_6910.jpg',
    ],
  },
  {
    slug: 'hotel-laico-tunis',
    name: 'Hotel Laico Tunis',
    category: 'Hôtel',
    location: 'Tunis',
    quote: 'Le jardin tropical — une architecture végétale entre modernité et tradition.',
    description:
      "Le jardin tropical de l'Hôtel Laico allie architecture contemporaine et éléments traditionnels. Des lignes épurées, un style moderne et une végétation généreuse accessible depuis de multiples angles offrent des vues panoramiques d'une rare qualité paysagère.",
    images: [
      '/projects/hotel-laico-tunis/MVS_7355.jpg',
      '/projects/hotel-laico-tunis/MVS_7363.jpg',
      '/projects/hotel-laico-tunis/MVS_7371.jpg',
      '/projects/hotel-laico-tunis/MVS_7378.jpg',
      '/projects/hotel-laico-tunis/MVS_7383.jpg',
      '/projects/hotel-laico-tunis/MVS_7391.jpg',
      '/projects/hotel-laico-tunis/MVS_7396.jpg',
      '/projects/hotel-laico-tunis/MVS_7401.jpg',
      '/projects/hotel-laico-tunis/MVS_7419.jpg',
    ],
  },
  {
    slug: 'the-orangers',
    name: 'The Orangers Garden Villas',
    category: 'Hôtel',
    location: 'Nabeul, Tunisie',
    quote: 'Cinq hectares d\'orangers, de jasmin et de palmiers au bord de la Méditerranée.',
    description:
      "Resort de luxe 5 étoiles sur les plages méditerranéennes de Nabeul. Cinq hectares de végétation exubérante — orangers, jasmin, palmiers, bougainvilliers, lavande, oliviers et Cycas revolutas — composent un paysage d'une richesse botanique exceptionnelle.",
    images: [
      '/projects/the-orangers/MVS_7702.jpg',
      '/projects/the-orangers/MVS_7705.jpg',
      '/projects/the-orangers/MVS_7706.jpg',
      '/projects/the-orangers/MVS_7711.jpg',
      '/projects/the-orangers/MVS_7712.jpg',
      '/projects/the-orangers/MVS_7720.jpg',
      '/projects/the-orangers/MVS_7723.jpg',
      '/projects/the-orangers/MVS_7725.jpg',
      '/projects/the-orangers/MVS_7727.jpg',
      '/projects/the-orangers/MVS_7728.jpg',
      '/projects/the-orangers/MVS_7730.jpg',
      '/projects/the-orangers/MVS_7731.jpg',
      '/projects/the-orangers/MVS_7734.jpg',
      '/projects/the-orangers/MVS_7739.jpg',
      '/projects/the-orangers/MVS_7743.jpg',
      '/projects/the-orangers/MVS_7744.jpg',
      '/projects/the-orangers/MVS_7748.jpg',
      '/projects/the-orangers/MVS_7749.jpg',
      '/projects/the-orangers/MVS_7752.jpg',
      '/projects/the-orangers/MVS_7753.jpg',
      '/projects/the-orangers/MVS_7754.jpg',
    ],
  },
  {
    slug: 'hotel-movenpick',
    name: 'Hôtel Mövenpick Lac',
    category: 'Hôtel',
    location: 'Lac 1, Tunis',
    quote: 'Un charme intemporel préservé grâce à un engagement indéfectible pour le développement durable.',
    description:
      "Réalisé il y a plus de 3 ans, ce projet hôtelier conserve tout son charme et sa beauté. SOPAT s'engage pour un développement durable garantissant que chaque réalisation perdure en parfait état, grâce à des équipes terrain dédiées et une végétation florissante.",
    images: [
      '/projects/hotel-movenpick/MVS_2082.jpg',
      '/projects/hotel-movenpick/MVS_4621.jpg',
      '/projects/hotel-movenpick/MVS_4629.jpg',
      '/projects/hotel-movenpick/MVS_4660.jpg',
      '/projects/hotel-movenpick/MVS_4674.jpg',
      '/projects/hotel-movenpick/MVS_4692.jpg',
      '/projects/hotel-movenpick/MVS_4699.jpg',
      '/projects/hotel-movenpick/MVS_4723.jpg',
      '/projects/hotel-movenpick/MVS_4724.jpg',
      '/projects/hotel-movenpick/MVS_4726.jpg',
      '/projects/hotel-movenpick/MVS_4729.jpg',
      '/projects/hotel-movenpick/MVS_4730.jpg',
      '/projects/hotel-movenpick/MVS_4733.jpg',
      '/projects/hotel-movenpick/MVS_4742.jpg',
      '/projects/hotel-movenpick/MVS_4755.jpg',
      '/projects/hotel-movenpick/MVS_4758.jpg',
      '/projects/hotel-movenpick/MVS_4761.jpg',
    ],
  },
  {
    slug: 'gat',
    name: 'GAT Assurances',
    category: 'Entreprise',
    location: 'Tunis',
    quote: 'Travailler avec vue sur un jardin — le bien-être au cœur de l\'espace professionnel.',
    description:
      "Jardin corporate créé pour le siège de GAT Assurances. La présence de plantes et de verdure réduit le stress des collaborateurs et améliore leur humeur au quotidien. Un investissement dans le bien-être qui se traduit directement en productivité et en créativité.",
    images: [
      '/projects/gat/1-1.jpg',
      '/projects/gat/2-1.jpg',
      '/projects/gat/3-1.jpg',
      '/projects/gat/4.jpg',
      '/projects/gat/5.jpg',
      '/projects/gat/6.jpg',
      '/projects/gat/7.jpg',
      '/projects/gat/8.jpg',
    ],
  },
  {
    slug: 'oradist',
    name: 'Oradist',
    category: 'Entreprise',
    location: 'Tunis',
    quote: 'Nous mettons la nature au service de vos équipes — l\'entreprise de demain est végétale.',
    description:
      "Terrasses, toitures, cours, jardins ou intérieur — SOPAT met la nature au service des équipes d'Oradist. Ce projet corporate traduit notre vision de l'entreprise de demain : des espaces verts pensés pour le bien-être des collaborateurs et la productivité.",
    images: [
      'https://www.sopat.tn/wp-content/uploads/2022/01/Fichier-1-1.png',
    ],
  },
  {
    slug: 'cafe-kube-lac-2',
    name: 'Café KUBE Lac 2',
    category: 'Restauration',
    location: 'Lac 2, Tunis',
    quote: 'Un écrin élégant où il fait bon s\'attarder — la nature au cœur du lieu de vie.',
    description:
      "Un écrin élégant où il fait bon boire un thé ou se délecter d'une douceur sucrée le temps d'une escale à Tunis. SOPAT a conçu l'aménagement paysager du Café KUBE pour créer une atmosphère végétale raffinée, en parfaite harmonie avec l'identité du lieu.",
    images: [
      'https://www.sopat.tn/wp-content/uploads/2020/08/kube-1.jpg',
    ],
  },
  {
    slug: 'gourmandise-lac',
    name: 'Maison Gourmandise',
    category: 'Restauration',
    location: 'Lac 1, Tunis',
    quote: 'Un espace sublime, conçu avec gratitude pour un client fidèle et partenaire de longue date.',
    description:
      "SOPAT exprime sa fierté d'avoir conçu et aménagé cet espace pour Maison Gourmandise, client fidèle et partenaire de confiance. Un projet de restauration où l'art du paysage rencontre l'art de recevoir, pour une expérience sensorielle complète.",
    images: [
      '/projects/gourmandise-lac/1.jpg',
      '/projects/gourmandise-lac/2.jpg',
      '/projects/gourmandise-lac/3.jpg',
      '/projects/gourmandise-lac/MVS_2562.jpg',
      '/projects/gourmandise-lac/MVS_2567.jpg',
      '/projects/gourmandise-lac/MVS_2569.jpg',
      '/projects/gourmandise-lac/MVS_2570.jpg',
    ],
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}

export function getAdjacentProjects(slug: string): { prev: Project | null; next: Project | null } {
  const index = projects.findIndex((p) => p.slug === slug)
  return {
    prev: index > 0 ? projects[index - 1] : null,
    next: index < projects.length - 1 ? projects[index + 1] : null,
  }
}
